knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration

        # will create service: "knpu.oauth2.client.foo_bar_oauth"
        # an instance of: KnpU\OAuth2ClientBundle\Client\OAuth2Client
        wiki_oauth:
            type: generic
            provider_class: App\Provider\WikiProvider

            # optional: a class that extends OAuth2Client
            # client_class: Some\Custom\Client

            # optional: if your provider has custom constructor options
            # provider_options: {}

            # now, all the normal options!
            client_id: '%env(BETA_OAUTH_WIKI_ID)%'
            client_secret: '%env(BETA_OAUTH_WIKI_SECRET)%'
            redirect_route: login_check_wiki_oauth
            redirect_params: { }
            # whether to check OAuth2 "state": defaults to true
            # use_state: true
